openapi: 3.0.0
info:
  title: UserAuthService API
  description: API for user authentication and management
  version: 1.0.0
servers:
  - url: '{{domain}}'

paths:
  /auth/login:
    post:
      summary: Login
      description: User login endpoint
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              example:
                username: test4
                password: testPassword
      responses:
        '200':
          description: Successful login
        '401':
          description: Unauthorized

  /users/:
    get:
      summary: Get users
      description: Retrieve a list of users
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '401':
          description: Unauthorized

  /users/register:
    post:
      summary: Register user
      description: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                displayName:
                  type: string
                email:
                  type: string
              example:
                username: test4
                password: testPassword
                displayName: testDisplayName
                email: nilesh.sarkar155@gmail.com
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Bad request

  /users/{userId}:
    patch:
      summary: Update user
      description: Update user details
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: The user ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                displayName:
                  type: string
              example:
                displayName: newTest3
      responses:
        '200':
          description: User updated successfully
        '404':
          description: User not found

    delete:
      summary: Delete user
      description: Delete a user by ID
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: The user ID
      responses:
        '204':
          description: User deleted successfully
        '404':
          description: User not found
